# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0b361dd4ba80bf659b6782f8ba937e5d5da8462f7dff02c3070521c457b1db9477ce7e23dccda0748e1fd660436c1e1eee80a36ae5416b3b1e711e3079a9c3d

test:
  secret_key_base: 3a7c19db2d6e5cda66a32c3f4c18a838ec47ab3506f8abd4b941ec6fbdd9b39a949c19b7b2678fe0aa411ee88b3da01443feba9ea3f1b2482c0213ca23b9ba5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
